source 'https://rubygems.org'

gem 'concurrent-ruby'
gem 'kitchen-ansible'
gem 'kitchen-docker'
gem 'kitchen-inspec'
gem 'kitchen-puppet'
gem 'kitchen-salt'
gem 'kitchen-vagrant'
gem 'kitchen-verifier-serverspec'
gem 'librarian-puppet'
gem 'serverspec'
gem 'test-kitchen'
