#!/usr/bin/env bash

set -eu

I3_REPO=https://github.com/JerusJ/i3-starterpack.git
I3_REPO_DEST="${HOME}"/i3-config

echo "--> Installing basic i3 packages..."
sudo apt-get install -y \
	i3 \
	i3-wm \
	dunst \
	i3lock \
	i3status \
	suckless-tools

echo "--> Installing desktop look-and-feel packages..."
sudo apt-get install -y \
	compton \
	hsetroot \
	rxvt-unicode \
	xsel \
	rofi \
	fonts-noto \
	fonts-mplus \
	xsettingsd \
	lxappearance \
	scrot \
	viewnior

echo "--> Cloning repository and copying config files..."
[ -d "${I3_REPO_DEST}" ] || git clone ${I3_REPO} ${I3_REPO_DEST}
[ -d ~/.config ] || mkdir -p ~/.config
[ -d ~/.config/dunst ] || ln -s ${I3_REPO_DEST}/.config/dunst ~/.config/dunst
[ -d ~/.config/i3 ] || ln -s ${I3_REPO_DEST}/.config/i3 ~/.config/i3
[ -d ~/.config/i3status ] || ln -s ${I3_REPO_DEST}/.config/i3status ~/.config/i3status
[ -d ~/.config/rofi/config ] || ln -s ${I3_REPO_DEST}/.config/rofi ~/.config/rofi
[ -f ~/.config/compton.conf ] || ln -s ${I3_REPO_DEST}/.config/compton.conf ~/.config/compton.conf
