#!/usr/bin/env bash

set -e
set -u

# Version Vars
export GOLANG_VERSION=1.13.8
export ANSIBLE_VERSION=2.9.11
export KUBECTL_VERSION=1.17.0
export KUSTOMIZE_VERSION=3.5.2
export TERRAFORM_VERSION=0.13.2
export TERRAGRUNT_VERSION=0.26.7
export PACKER_VERSION=1.4.5
export HELM_VERSION=3.1.1
export JUMP_VERSION=0.30.1
export VAGRANT_VERSION=2.2.0

# Golang Vars
# export GOPATH=/go
# export GOROOT=/usr/local/go
# export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH

# echo "--> Disabling Mouse Acceleration..."
# sudo cat <<EOF >/usr/share/X11/xorg.conf.d/50-mouse-acceleration.conf
# Section "InputClass"
#     Identifier "My Mouse"
#     MatchIsPointer "yes"
#     Option "AccelerationProfile" "-1"
#     Option "AccelerationScheme" "none"
#     Option "AccelSpeed" "-1"
# EndSection
# EOF

# Build/Network General Utilities
echo "--> Installing General Utilities..."
sudo apt-get update && sudo apt-get install -y --no-install-recommends \
  build-essential \
  git \
  ca-certificates \
  gcc \
  make \
  apt-transport-https \
  ca-certificates \
  curl \
  iproute2 \
  gnupg2 \
  software-properties-common \
  unzip \
  sshpass \
  bash \
  jq \
  openssh-client \
  libnss3-tools \
  curl \
  rbenv \
  python3-gpg \

echo "--> Installing Python..."
sudo apt-get install -y python3-pip python3-venv

echo "--> Installing Golang..."
sudo apt-get install -y golang

echo "--> Installing Pip Packages for Setup..."
pip3 install --no-cache-dir --upgrade \
  pip \
  setuptools \
  suds-jurko \
  requests

echo "--> Installing Python Packages for Linters..."
pip3 install --no-cache-dir \
  pylint \
  appdirs \
  attrs \
  click \
  entrypoints \
  flake8 \
  isort \
  mccabe \
  mypy-extensions \
  mypy \
  pycodestyle \
  pyflakes \
  toml \
  typed-ast \
  typing-extensions \
  unify \
  untokenize \
  yapf \
  ansible-lint \
  yamllint

echo "--> Installing Python Packages for Documentation..."
pip3 install --no-cache-dir \
  sphinx \
  sphinx_rtd_theme

echo "--> Installing Python Packages for Ansible..."
pip3 install --no-cache-dir \
  ansible==${ANSIBLE_VERSION} \
  molecule \
  pyvmomi \
  jmespath \
  pywinrm \
  pexpect \
  boto \
  boto3 \
  botocore

echo "--> Installing Python Packages for Tests..."
pip3 install --no-cache-dir \
  pytest \
  pytest-cov \
  pytest-dependency \
  pytest-timeout \
  pytest-html \
  pytest-selenium \
  pytest-xdist \
  kubernetes \
  testinfra \
  paramiko

if [ ! -f "/usr/bin/docker" ]; then
  echo "--> Installing Docker..."
  sudo apt-get -y install docker.io
fi

if [ ! -f "/usr/bin/docker-compose" ]; then
  echo "--> Installing Docker-Compose..."
  sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  sudo chmod +x /usr/local/bin/docker-compose
fi

if [ ! -f /usr/local/bin/kubectl ]; then
  echo "--> Installing Kubectl ${KUBECTL_VERSION}..."
  sudo curl -L -o /usr/local/bin/kubectl \
    https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl &&
    sudo chmod +x /usr/local/bin/kubectl
fi

if [ ! -f /usr/local/bin/kustomize ]; then
  echo "--> Installing Kustomize ${KUSTOMIZE_VERSION}..."
  sudo curl -L \
    https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz |
    tar -xzvC /usr/local/bin/
fi

if [ ! -f /usr/local/bin/terraform ]; then
  echo "--> Installing Terraform ${TERRAFORM_VERSION}..."
  sudo curl -fsSL https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -o /tmp/terraform.zip &&
    sudo unzip /tmp/terraform.zip -d /usr/local/bin &&
    rm /tmp/terraform.zip
fi

if [ ! -f /usr/local/bin/terragrunt ]; then
   echo "--> Installing Terragrunt ${TERRAGRUNT_VERSION}..."
   sudo curl -L -o /usr/local/bin/terragrunt \
     https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64 \
     && sudo chmod +x /usr/local/bin/terragrunt
fi

if [ ! -f /usr/local/bin/packer ]; then
  echo "--> Installing Packer ${PACKER_VERSION}..."
  sudo curl -fsSl https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip -o /tmp/packer.zip &&
    sudo unzip /tmp/packer.zip -d /usr/local/bin &&
    sudo rm /tmp/packer.zip
fi

if [ ! -f /usr/local/bin/helm ]; then
  echo "--> Installing Helm ${HELM_VERSION}..."
  sudo curl -L https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz |
    tar -xz &&
    sudo mv linux-*/helm /usr/local/bin &&
    sudo rm -rf linux-*
fi

if [ ! -f /usr/local/bin/vagrant ]; then
  echo "--> Installing Vagrant ${VAGRANT_VERSION}..."
  sudo curl -fsSl https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_linux_amd64.zip /tmp/vagrant.zip &&
    sudo unzip /tmp/vagrant.zip -d /usr/local/bin &&
    sudo rm /tmp/vagrant.zip
fi

echo "--> Installing Personal Applications..."
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor >packages.microsoft.gpg || true
sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
sudo add-apt-repository -y ppa:lutris-team/lutris

sudo apt-get update -y
sudo apt-get install -y \
  code \
  vlc \
  silversearcher-ag \
  zsh \
  zsh-syntax-highlighting \
  zsh-autosuggestions \
  tree \
  bpython \
  vlc \
  redshift-gtk \
  pavucontrol

echo "--> Installing Mouse/DPI Utilities..."
sudo apt-get install -y \
  ratbagd \
  piper

wget https://github.com/gsamokovarov/jump/releases/download/v${JUMP_VERSION}/jump_${JUMP_VERSION}_amd64.deb
sudo dpkg -i jump_${JUMP_VERSION}_amd64.deb
sudo rm -f jump_${JUMP_VERSION}_amd64.deb

git clone https://github.com/rbenv/rbenv.git ~/.rbenv || true
git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build || true
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm || true

echo "--> Setting up nvim to load .vimrc..."
NVIM_CONFIG_FILE_PATH=~/.config/nvim/init.vim
mkdir -p $(dirname ${NVIM_CONFIG_FILE_PATH})
if [ ! -f "${NVIM_CONFIG_FILE_PATH}" ]; then
  echo "--> Creating ${NVIM_CONFIG_FILE_PATH}..."
  cat <<EOF >~/.config/nvim/init.vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath=&runtimepath
source ~/.vimrc
EOF
fi
