name: Build Installers

on: push

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Make
        run: sudo apt-get install -y make

      - name: Run Installer
        run: make
  mac:
    name: mac
    runs-on: macos-11.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Installer
        run: make
